### ISSUE TITLE
Device information for "Wacom Bamboo One M" not found.

### ISSUE THREAD

**Issue by Shadow429** [tb2097/wacom-gui#42]
Recently I've switched to Linux and decided to use my tablet, definitely got tired of setting work area via terminal commands.
My tablet: One by Wacom M / CTL-671
Unfortunately I'm receiving 2 errors while launching wacom-gui:
![obraz](https://user-images.githubusercontent.com/38445373/77102465-2a063d00-6a19-11ea-82c6-c4c6462af7d8.png)
After that, said GUI shows nothing - no model, no available options, basically nothing - I can try to refresh connected device but (put title of this issue here) error pops up.

When launching with terminal (not sure if important):

> (python:23552): dbind-WARNING **: 19:37:47.222: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

xsetwacom list:

> Wacom Bamboo One M Pen stylus   	id: 10	type: STYLUS    
Wacom Bamboo One M Pen eraser   	id: 11	type: ERASER  

and at last, libwacom-list-local-devices --database /usr/local/wacom-gui/data

> [Device]
Name=One by Wacom (medium)
ModelName=
DeviceMatch=usb:056a:0301;
Class=Bamboo
Width=9
Height=5
IntegratedIn=
Styli=0xffffe;0xfffff;
[Features]
Reversible=true
Stylus=true
Ring=false
Ring2=false
Touch=false
TouchSwitch=false
(there was hash sign here) StatusLEDs=
NumStrips=0
Buttons=0
---------------------------------------------------------------

**Comment by tb2097** [comment]
Greetings,
This is caused by a naming mismatch between the .tablet file and how the driver present itself.  Can you please edit the file `one-by-wacom-m-p.tablet` and set "Name=" to `Wacom Bamboo One M`? This should resolve the issue and I can submit the change to libwacom.  I've encountered a few of these occurrences already.

**Comment by Shadow429** [comment]
![obraz](https://user-images.githubusercontent.com/38445373/77232352-ceff5200-6ba0-11ea-8e75-7b55c33b4946.png)

I've modified it, checked "libwacom-list-local-devices --database /usr/local/wacom-gui/data" just in case:

> [Device]
Name=Wacom Bamboo One M
ModelName=
DeviceMatch=usb:056a:0301;
Class=Bamboo
Width=9
Height=5
IntegratedIn=
Styli=0xffffe;0xfffff;

Launched wacom-gui again to test if it works correctly, but error still pops up.

**Comment by tb2097** [comment]
Can you please run it via the terminal and copy the output? I have a vague suspicion of what might be going on but since I don't have one of those tablets I can't be sure.

**Comment by Shadow429** [comment]
I ran the "wacom-gui.py" in terminal, but there is no output.

![obraz](https://user-images.githubusercontent.com/38445373/77258808-45718200-6c7d-11ea-8e29-372532d80821.png)

And yes, errors still show up with the "Device information not found" just like before.

**Comment by 4l1fe** [comment]
I have the same issue but with the model CTL-672. After replacing to an actual **Name** got errors again.

**Comment by tb2097** [comment]
I think this may have something to do with the fact the tablet doesn't have any buttons, which I may not be handling correctly...
Can you please replace the `wacom_data.py` with this one: `https://github.com/tb2097/wacom-gui/blob/tb2097-no-buttons-debug/wacom-gui/wacom_data.py`

It should spit out the tablet info that is collected in terminal; hopefully it will inform me as to what is occurring so I can fix it for you.

**Comment by Shadow429** [comment]
> (python:3561): dbind-WARNING **: 00:18:39.390: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

(this one seems to appear at random, it didn't show up few days ago when providing info from terminal)
Other than that - nothing, still receiving errors about "device information not found"
Unless it was not directed to me - in such case, sorry.

**Comment by Shadow429** [comment]
I did this CORRECTLY this time (yeah, I should not do anything past midnight...sorry about that)
that's the output:

> r$ python wacom-gui.py
{'': {'cursor': {},
      'devID': '0301',
      'eraser': {},
      'pad': {'attr': {}, 'buttons': {}},
      'stylus': {'rotate': True},
      'touch': {}},
 'Wacom Bamboo One M': {'cursor': {},
                        'eraser': {},
                        'pad': {'attr': {}, 'buttons': {}},
                        'stylus': {},
                        'touch': {}}}
{'': {'cursor': {},
      'devID': '0301',
      'eraser': {},
      'pad': {'attr': {}},
      'stylus': {'rotate': True},
      'touch': {}},
 'Wacom Bamboo One M': {'cursor': {},
                        'eraser': {},
                        'pad': {'attr': {}},
                        'stylus': {},
                        'touch': {}}}


![obraz](https://user-images.githubusercontent.com/38445373/77851331-e231a380-71d8-11ea-9210-f4b819583361.png)

**Comment by dpcherian** [comment]
Hello! 

I'm not sure if I should start a new issue or continue this one, since I think I'm having the same problem with the CTL-672. As suggested, I began by editing `one-by-wacom-m-p2.tablet` and set `Name=` to "Wacom One by Wacom M" (since that was the name given in the error message. The original name was "One by Wacom (medium)").

The same error message still pops up when I run `wacom-gui.py`, and the tablet doesn't show up either.

I replaced the `wacom_data.py` file as suggested, and this is my output:

`{'Wacom One by Wacom M': {'cursor': {},
                          'devID': '037b',
                          'eraser': {},
                          'pad': {'attr': {}, 'buttons': {}},
                          'stylus': {'rotate': True},
                          'touch': {}}}
{'Wacom One by Wacom M': {'cursor': {},
                          'devID': '037b',
                          'eraser': {},
                          'pad': {'attr': {}},
                          'stylus': {'rotate': True},
                          'touch': {}}}
`
![image](https://user-images.githubusercontent.com/19914486/78782339-7f51c080-79bf-11ea-8b5e-1eec82dc75c9.png)

Do let me know if you've found a way to fix this!

**Comment by tb2097** [comment]
Apologies, real life is taking away from my free time.  Can you please replace the `wacom_data.py` with the file here: https://github.com/tb2097/wacom-gui/blob/tb2097-no-buttons-debug/wacom-gui/wacom_data.py

I have added some further debugging to try and figure out where it's crashing out. My guess is _something_ about how a pad without buttons is being detected is failing the check and therefore not being loaded.

**Comment by Shadow429** [comment]
![Selectionshot_2020-04-09_12:43:08](https://user-images.githubusercontent.com/38445373/78887302-e58e2000-7a5f-11ea-8470-3055b5444e6e.png)
Here's the output.

**Comment by dpcherian** [comment]
Hello,
Thank you for taking the time to do this!

![image](https://user-images.githubusercontent.com/19914486/79048140-9818db00-7c38-11ea-88f0-1380470acd08.png)

**Comment by karlchenotto** [comment]
I have the same problem with a "Wacom Cintiq 16". There was no entry in the /usr/share/wacomtablet/data/wacom_devicelist. However adding

`[0390]
model=DTK-1660
layout=unknown
name=Wacom Cintiq 16
padbuttons=0
wheel=no
touchring=no
touchstripl=no
touchstripr=no`

did not change anything.


I tried this:
> Can you please replace the wacom_data.py with the file here: https://github.com/tb2097/wacom-gui/blob/tb2097-no-buttons-debug/wacom-gui/wacom_data.py
 
This gave me:

`Traceback (most recent call last):
  File "wacom-gui.py", line 13, in <module>
    from wacom_data import Tablets
  File "/home/markus/Downloads/wacom/wacom-gui-master/wacom-gui/wacom_data.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
`

Thanks in advance four your help.

**Comment by Kuratius** [comment]
libwacom-list-local-devices
# Device node: /dev/input/event3
[Device]
Name=Wacom Intuos S
ModelName=CTL-4100
DeviceMatch=usb:056a:0374;
Class=Bamboo
Width=6
Height=4
IntegratedIn=
Layout=intuos-s-p3.svg
Styli=0x862;

[Features]
Reversible=false
Stylus=true
Ring=false
Ring2=false
Touch=false
TouchSwitch=false
# StatusLEDs=
NumStrips=0
Buttons=4

[Buttons]
# Left=
# Right=
Top=A;B;C;D;
# Bottom=
# Touchstrip=
# Touchstrip2=
# OLEDs=
# Ring=
# Ring2=
EvdevCodes=0x100;0x101;0x102;0x103;
RingNumModes=0
Ring2NumModes=0
StripsNumModes=0

---------------------------------------------------------------
# Device node: /dev/input/event2
[Device]
Name=Wacom Intuos S
ModelName=CTL-4100
DeviceMatch=usb:056a:0374;
Class=Bamboo
Width=6
Height=4
IntegratedIn=
Layout=intuos-s-p3.svg
Styli=0x862;

[Features]
Reversible=false
Stylus=true
Ring=false
Ring2=false
Touch=false
TouchSwitch=false
# StatusLEDs=
NumStrips=0
Buttons=4

[Buttons]
# Left=
# Right=
Top=A;B;C;D;
# Bottom=
# Touchstrip=
# Touchstrip2=
# OLEDs=
# Ring=
# Ring2=
EvdevCodes=0x100;0x101;0x102;0x103;
RingNumModes=0
Ring2NumModes=0
StripsNumModes=0

---------------------------------------------------------------



python2 wacom-gui.py 
/bin/sh: 1: dconf: not found
sh: 1: dconf: not found
{'CTL-4100': {'cursor': {},
              'devID': '0374',
              'eraser': {},
              'pad': {'attr': {},
                      'buttons': {'ButtonA': {'bid': 'Button 1',
                                              'orient': 'Top'},
                                  'ButtonB': {'bid': 'Button 2',
                                              'orient': 'Top'},
                                  'ButtonC': {'bid': 'Button 3',
                                              'orient': 'Top'},
                                  'ButtonD': {'bid': 'Button 8',
                                              'orient': 'Top'}}},
              'stylus': {'rotate': False},
              'svg': 'intuos-s-p3.svg',
              'touch': {}},
 'Wacom Intuos S': {'cursor': {},
                    'eraser': {},
                    'pad': {'attr': {}, 'buttons': {}},
                    'stylus': {},
                    'touch': {}}}
invalid literal for float(): 42,10.5
{'CTL-4100': {'cursor': {},
              'devID': '0374',
              'eraser': {},
              'pad': {'attr': {},
                      'buttons': {'ButtonA': {'bid': 'Button 1',
                                              'orient': 'Top'},
                                  'ButtonB': {'bid': 'Button 2',
                                              'orient': 'Top'},
                                  'ButtonC': {'bid': 'Button 3',
                                              'orient': 'Top'},
                                  'ButtonD': {'bid': 'Button 8',
                                              'orient': 'Top'}}},
              'stylus': {'rotate': False},
              'svg': 'intuos-s-p3.svg',
              'touch': {}},
 'Wacom Intuos S': {'cursor': {},
                    'eraser': {},
                    'pad': {'attr': {}},
                    'stylus': {},
                    'touch': {}}}
invalid literal for float(): 42,10.5
^CTraceback (most recent call last):
  File "wacom-gui.py", line 436, in closeEvent
    def closeEvent(self, event):
KeyboardInterrupt

**Comment by tb2097** [comment]
@karlchenotto 

I think you may not have downloaded wacom_data.py correctly... can you use this? https://raw.githubusercontent.com/tb2097/wacom-gui/tb2097-no-buttons-debug/wacom-gui/wacom_data.py

@Kuratius 

Which linux distro/desktop frontend are you using? It is throwing an error for using dconf, which is used to set hotkeys.

**Comment by Kuratius** [comment]
@tb2097 Xubuntu with xfce.
I am getting the "Device information for Wacom Intuos S not found" error also.

**Comment by ForumPlayer** [comment]
> @tb2097 Xubuntu with xfce.
> I am getting the "Device information for Wacom Intuos S not found" error also.

The same on Debian 10 (with OpenBox)

**Comment by zyrmpg** [comment]
I'm getting a similar error dialog with a Wacom Intuos S but with `invalid literal for float(): 42,10.5` output.

Appears to be same as @Kuratius without the dconf errors. I'm on Ubuntu 19.10/Xfce

**`wacom-gui.py` w/ modified `wacom_data.py`:**
```
{'CTL-4100': {'cursor': {},
              'devID': '0374',
              'eraser': {},
              'pad': {'attr': {},
                      'buttons': {'ButtonA': {'bid': 'Button 1',
                                              'orient': 'Top'},
                                  'ButtonB': {'bid': 'Button 2',
                                              'orient': 'Top'},
                                  'ButtonC': {'bid': 'Button 3',
                                              'orient': 'Top'},
                                  'ButtonD': {'bid': 'Button 8',
                                              'orient': 'Top'}}},
              'stylus': {'rotate': False},
              'svg': 'intuos-s-p3.svg',
              'touch': {}},
 'Wacom Intuos S': {'cursor': {},
                    'eraser': {},
                    'pad': {'attr': {}, 'buttons': {}},
                    'stylus': {},
                    'touch': {}}}
invalid literal for float(): 42,10.5
{'CTL-4100': {'cursor': {},
              'devID': '0374',
              'eraser': {},
              'pad': {'attr': {},
                      'buttons': {'ButtonA': {'bid': 'Button 1',
                                              'orient': 'Top'},
                                  'ButtonB': {'bid': 'Button 2',
                                              'orient': 'Top'},
                                  'ButtonC': {'bid': 'Button 3',
                                              'orient': 'Top'},
                                  'ButtonD': {'bid': 'Button 8',
                                              'orient': 'Top'}}},
              'stylus': {'rotate': False},
              'svg': 'intuos-s-p3.svg',
              'touch': {}},
 'Wacom Intuos S': {'cursor': {},
                    'eraser': {},
                    'pad': {'attr': {}},
                    'stylus': {},
                    'touch': {}}}
invalid literal for float(): 42,10.5
```

**Comment by tb2097** [comment]
Please try using the latest release: https://github.com/tb2097/wacom-gui/releases/tag/v0.3.0-rc18, let me know if this resolves the issue.

**Comment by fopor** [comment]
Having this problem on Arch
![image](https://user-images.githubusercontent.com/29164832/106647291-7ee96e00-656d-11eb-8eb9-851d787fae88.png)

**Comment by Origami404** [comment]
Having this problem on Fedora 35 with CTL-672
